### PR TITLE
upgrade to 2.176.1

### PR DESCRIPTION
**Pull request by yalh76**

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
It doesn't work.
The error is "-remoting mode is no longer supported" when installing plugins.

**Comment by yalh76** [comment]
> it doesn't work.
> The error is "-remoting mode is no longer supported" when installing plugins.

I've read https://jenkins.io/blog/2019/02/17/remoting-cli-removed/ but didn't find a way to do without the `-remoting` I will remove my PR :///

**Comment by maniackcrudelis** [comment]
Huh, even if I'm getting tired of this fucking jenkins which modify the way it works every fucking version, don't you think we should try to fix it and get the upgrade done ?

**Comment by yalh76** [comment]
I 200% agree with you, we should try to fix it, but I haven't the time for that for now, It's why I postponed jenkins upgrade.

And maybe we should look at a Jenkins [replacement](https://en.wikipedia.org/wiki/Comparison_of_continuous_integration_software)

I don't know if gitlab would be a [good CI](https://docs.gitlab.com/ee/ci/) but could be interesting to look at it, as it seems that there is also [ActivityPub ForgeFed](https://notabug.org/peers/forgefed) work ongoing

**Comment by maniackcrudelis** [comment]
We have already replaced it for our own usage by YunoRunner.
But here's it's mostly about the Jenkins app itself, guess some would use it.

**Pull request closed without merging**
